import { describe, expect, it } from 'vitest';
import { cleaningProgress, resortGoal, upgradeBenefit } from './Guidance';
import { initialResort, LEVELS, ROOM_WORK, ROOM_DEFS } from './data';
import { ResortSimulation } from './Simulation';
import { validResort } from './SaveService';
const advance = (s: ResortSimulation, time: number) => { for (let i = 0; i < time * 10; i++) s.tick(.1); };
describe('guided, satisfying first session', () => {
  it('introduces a visitor within three seconds without changing the starting inventory', () => { const s = new ResortSimulation(); advance(s, 3); expect(s.state.guests).toHaveLength(1); expect(s.state.money).toBe(0); expect(s.state.laundry.clean).toBe(8); expect(validResort(s.state)).toBe(true); });
  it('uses shorter introductory stays and normal stays afterwards', () => { for (const [stays, duration] of [[0, 12], [1, 18], [2, 24], [3, 40]]) { const s = new ResortSimulation(); s.state.stats.welcomed = 1; s.state.stats.stays = stays; const p = ROOM_WORK(ROOM_DEFS[0]); s.state.guests.push({ id: 'guest1', ...p, phase: 'toRoom', path: [], remaining: 0, room: 'room1' }); s.facility('room1').guest = 'guest1'; s.tick(.1); expect(s.state.guests[0].remaining).toBe(duration); } });
  it('unlocks the second room after a stay and its cleanup', () => { expect(LEVELS[1]).toBe(15); const s = new ResortSimulation(); s.state.xp = 10; s.facility('room1').dirty = true; Object.assign(s.state.player, ROOM_WORK(ROOM_DEFS[0])); advance(s, 7); expect(s.level).toBe(2); expect(s.state.xp).toBe(15); });
  it('does not point to laundry or an empty cash pad after the first check-in when no supplies are needed', () => { const s = initialResort(); s.stats.welcomed = 1; expect(resortGoal(s).area).toBe(''); s.player.bag.clean = 2; expect(resortGoal(s).title).toBe('Misafirin dinleniyor'); expect(resortGoal(s).area).toBe(''); });
  it('still directs the player to laundry when a room actually needs towels or sheets before the first stay ends', () => { const s = initialResort(); s.stats.welcomed = 1; const room = s.facilities.find(f => f.id === 'room1')!; room.towels = 0; expect(resortGoal(s).area).toBe('cleanTake'); room.towels = 1; room.needsSheet = true; expect(resortGoal(s).area).toBe('cleanTake'); });
  it('directs first earnings to the cash pile', () => { const s = initialResort(); s.stats.welcomed = 1; s.stats.stays = 1; s.facilities[0].cash = 40; expect(resortGoal(s).area).toBe('receptionCash'); });
  it('routes a full bag to laundry before cleaning', () => { const s = initialResort(); s.stats.welcomed = 1; s.stats.stays = 1; s.stats.earned = 40; s.facilities.find(f => f.id === 'room1')!.dirty = true; s.player.bag = { clean: 4, dirty: 4 }; expect(resortGoal(s).area).toBe('dirtyDrop'); });
  it('routes freshly collected dirty linen to the hamper before clean linen', () => { const s = initialResort(); s.stats.welcomed = s.stats.stays = s.stats.cleaned = 1; s.stats.earned = 40; const room = s.facilities.find(f => f.id === 'room1')!; room.towels = 0; s.player.bag.dirty = 1; expect(resortGoal(s).area).toBe('dirtyDrop'); expect(resortGoal(s).body).toContain('çamaşır sepetine'); s.player.bag.dirty = 0; expect(resortGoal(s).area).toBe('cleanTake'); });
  it('prioritizes making a cleaned room ready even when another room is dirty', () => { const s = initialResort(); s.stats.welcomed = s.stats.stays = s.stats.cleaned = 1; s.stats.earned = 40; s.facilities.find(f => f.id === 'room1')!.towels = 0; const second = s.facilities.find(f => f.id === 'room2')!; second.open = second.dirty = true; expect(resortGoal(s).area).toBe('cleanTake'); s.player.bag.clean = 1; expect(resortGoal(s).area).toBe('room1Work'); });
  it('does not leave the washing quest stuck at an empty dirty-drop square', () => { const s = initialResort(); s.stats.welcomed = s.stats.stays = s.stats.cleaned = 1; s.stats.earned = 40; s.laundry.remaining = 3; expect(resortGoal(s).area).toBe('checkin'); s.laundry.remaining = null; s.stats.washed = 1; s.xp = 15; expect(resortGoal(s).area).toBe('room2Buy'); });
  it('guides through all six rooms before unlocking the pool', () => {
    const sim = new ResortSimulation();
    sim.hire('rooms');
    sim.state.stats.welcomed = sim.state.stats.stays = sim.state.stats.cleaned = sim.state.stats.washed = sim.state.stats.earned = 1;
    sim.state.xp = 280;
    for (const id of ['room2', 'room3', 'room4', 'room5']) sim.facility(id).open = true;
    expect(sim.area('poolBuy')).toBeDefined();
    expect(sim.areas.some(a => a.id.startsWith('pool') && a.id !== 'poolBuy')).toBe(false);
    expect(resortGoal(sim.state).area).toBe('room6Buy');
    sim.facility('room6').open = true;
    expect(resortGoal(sim.state).area).toBe('poolBuy');
  });
  it('describes measurable upgrade benefits', () => { expect(upgradeBenefit('room1', 1)).toContain('50 ₺'); expect(upgradeBenefit('room1', 2)).toBe('En yüksek oda seviyesi'); expect(upgradeBenefit('laundry', 2)).toContain('7 parça'); });
  it('clamps visual cleaning progress without modifying tasks', () => { expect(cleaningProgress(3, 6)).toBe(.5); expect(cleaningProgress(-1, 6)).toBe(1); expect(cleaningProgress(10, 6)).toBe(0); expect(cleaningProgress(0, 0)).toBe(0); });
  it('generates transient feedback without changing saved resources', () => { const s = new ResortSimulation(); s.facility('reception').cash = 40; Object.assign(s.state.player, s.area('receptionCash')); s.tick(.1); expect(s.state.money).toBe(40); expect(s.feedback.some(e => e.kind === 'cash' && e.text === '+40 ₺')).toBe(true); expect(JSON.stringify(s.state)).not.toContain('feedback'); const resumed = new ResortSimulation(structuredClone(s.state)); expect(resumed.feedback).toHaveLength(0); });
  it('freezes feedback and cleaning progress when paused', () => { const s = new ResortSimulation(); s.facility('room1').dirty = true; Object.assign(s.state.player, ROOM_WORK(ROOM_DEFS[0])); advance(s, 2); s.state.settings.paused = true; const before = JSON.stringify(s.state); const feedback = JSON.stringify(s.feedback); advance(s, 5); expect(JSON.stringify(s.state)).toBe(before); expect(JSON.stringify(s.feedback)).toBe(feedback); });
});
