import type { GuestState, Point } from './types';
export const BAR_CENTER = { x: 28.5, y: -1 };
export const BAR_WORK = { x: 28.5, y: -3 };
export const BAR_CASH = { x: 25, y: -1 };
export const BAR_HIRE = { x: 32, y: -1 };
export const POOL_TOWEL_RACK = { x: 34.5, y: 0 };
export const POOL_DIRTY_RACK = { x: 34.5, y: 3 };
export const poolTowelRack = (level: number): Point => level >= 2 ? { x: 37, y: 0 } : POOL_TOWEL_RACK;
export const poolDirtyRack = (level: number): Point => level >= 2 ? { x: 37, y: 3 } : POOL_DIRTY_RACK;
export const POOL_CENTER = { x: 28.5, y: 4.5 };
export const POOL_STAY_SECONDS = 150;
export const DRINK_REQUEST_DELAY = 20;
export const insideBar = (p: Point) => Math.abs(p.x - BAR_CENTER.x) <= 2.1 && Math.abs(p.y - BAR_CENTER.y) <= 1.025;
export const POOL_CLEAN = { x: 22, y: 5 };
export const wantsDrink = (g: GuestState) => g.phase === 'swimming' && !!g.drinkRequested && !g.drinkServed;
export const atPoolEdge = (p: Point, level = 1) => {
  const halfWidth = level >= 2 ? 6.35 : 4.5, halfDepth = level >= 2 ? 3.45 : 2.5;
  const left = POOL_CENTER.x - halfWidth, right = POOL_CENTER.x + halfWidth, top = POOL_CENTER.y - halfDepth, bottom = POOL_CENTER.y + halfDepth;
  const inside = p.x >= left && p.x <= right && p.y >= top && p.y <= bottom;
  return !inside && Math.hypot(Math.max(left - p.x, 0, p.x - right), Math.max(top - p.y, 0, p.y - bottom)) <= 2;
};
