export interface Point { x: number; y: number }
export interface Towels { clean: number; dirty: number; cleanSheets?: number; dirtySheets?: number }
export interface Actor extends Point { id: string; path: Point[] }
export type Role = 'reception' | 'rooms' | 'pool' | 'hauling' | 'bartender';
export type TaskKind = 'checkin' | 'cleanRoom' | 'cleanFloor' | 'cleanBathroom' | 'restockRoom' | 'cleanPool' | 'prepareDrink' | 'deliverDrink' | 'cleanTake' | 'poolCheckin' | 'cleanSeat' | 'poolStock' | 'dirtyDrop' | 'poolDirtyDrop' | 'poolDirtyTake' | 'poolCleanTake' | 'restockSeat' | 'laundryDirtyTake' | 'machineLoad' | 'machineUnload' | 'laundryCleanDrop' | 'discardItem';
export interface TaskState { id: string; kind: TaskKind; target: string; owner: string; remaining: number; total: number; guest?: string; destination?: string }
export interface PlayerState extends Actor { bag: Towels; task?: string; drink?: boolean; heldProduct?: 'lemonade' | 'icecream'; carryingWashed?: boolean }
export interface WorkerState extends Actor { name: string; role: Role; level: number; carryLevel?: number; moveLevel?: number; bag: Towels; task?: string; status: string; drink?: boolean; heldProduct?: 'lemonade' | 'icecream'; carryingWashed?: boolean }
export interface GuestState extends Actor { phase: 'queue' | 'toRoom' | 'staying' | 'toPool' | 'poolQueue' | 'toSeat' | 'swimming' | 'leaving'; room?: string; seat?: string; remaining: number; queueWait?: number; worstWait?: number; drinkRequested?: boolean; drinkServed?: boolean; orderProduct?: 'lemonade' | 'icecream'; visitsPool?: boolean; wantsLemonade?: boolean; poolActivity?: 'swim' | 'relax' }
export interface FacilityState { id: string; kind: 'reception' | 'room' | 'laundry' | 'pool'; open: boolean; level: number; dirty: boolean; floorDirty?: boolean; bathroomDirty?: boolean; needsSheet?: boolean; towels: number; guest?: string; cash: number; tips?: number; dirt?: number; dirtyTowels?: number }
export interface SeatState { id: string; open: boolean; dirty: boolean; guest?: string; towel?: boolean }
export interface LaundryState { dirty: number; clean: number; remaining: number | null; cleanSheets?: number; dirtySheets?: number; washingTowels?: number; washingSheets?: number; washingKind?: 'towel' | 'sheet' }
export interface ResortGameState { version: 1; concept: 'ege-resort'; money: number; xp: number; elapsed: number; spawnTimer: number; nextId: number; bar?: { open: boolean; cash: number }; player: PlayerState; guests: GuestState[]; workers: WorkerState[]; facilities: FacilityState[]; seats: SeatState[]; laundry: LaundryState; tasks: TaskState[]; boost: { remaining: number; multiplier: number }; settings: { paused: boolean; speed: 1 | 2; volume?: number }; stats: { welcomed: number; stays: number; cleaned: number; washed: number; poolVisits: number; earned: number } }
export interface Area extends Point { id: string; label: string; mode: 'work' | 'buy' | 'upgrade' | 'cash'; target: string; taskKind?: TaskKind }
